// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJjP-avXJ0btdDrS-hZr5mUQmm2Ieet-g',
    appId: '1:170226610519:web:0424fea5ce2ce5aa598e12',
    messagingSenderId: '170226610519',
    projectId: 'projectshowcase-56c2b',
    authDomain: 'projectshowcase-56c2b.firebaseapp.com',
    storageBucket: 'projectshowcase-56c2b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJjP-avXJ0btdDrS-hZr5mUQmm2Ieet-g',
    appId: '1:170226610519:android:0424fea5ce2ce5aa598e12',
    messagingSenderId: '170226610519',
    projectId: 'projectshowcase-56c2b',
    storageBucket: 'projectshowcase-56c2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJjP-avXJ0btdDrS-hZr5mUQmm2Ieet-g',
    appId: '1:170226610519:ios:0424fea5ce2ce5aa598e12',
    messagingSenderId: '170226610519',
    projectId: 'projectshowcase-56c2b',
    storageBucket: 'projectshowcase-56c2b.firebasestorage.app',
    iosBundleId: 'com.example.projectshowcase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJjP-avXJ0btdDrS-hZr5mUQmm2Ieet-g',
    appId: '1:170226610519:ios:0424fea5ce2ce5aa598e12',
    messagingSenderId: '170226610519',
    projectId: 'projectshowcase-56c2b',
    storageBucket: 'projectshowcase-56c2b.firebasestorage.app',
    iosBundleId: 'com.example.projectshowcase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJjP-avXJ0btdDrS-hZr5mUQmm2Ieet-g',
    appId: '1:170226610519:web:0424fea5ce2ce5aa598e12',
    messagingSenderId: '170226610519',
    projectId: 'projectshowcase-56c2b',
    authDomain: 'projectshowcase-56c2b.firebaseapp.com',
    storageBucket: 'projectshowcase-56c2b.firebasestorage.app',
  );
}
