// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUduwQCS_4HXaEmn_Ilf57BxDA9DT865g',
    appId: '1:279672202046:web:b409f9affe2a8bd4fd826f',
    messagingSenderId: '279672202046',
    projectId: 'projectshowcase-b2748',
    authDomain: 'projectshowcase-b2748.firebaseapp.com',
    storageBucket: 'projectshowcase-b2748.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUduwQCS_4HXaEmn_Ilf57BxDA9DT865g',
    appId: '1:279672202046:android:b409f9affe2a8bd4fd826f',
    messagingSenderId: '279672202046',
    projectId: 'projectshowcase-b2748',
    storageBucket: 'projectshowcase-b2748.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUduwQCS_4HXaEmn_Ilf57BxDA9DT865g',
    appId: '1:279672202046:ios:b409f9affe2a8bd4fd826f',
    messagingSenderId: '279672202046',
    projectId: 'projectshowcase-b2748',
    storageBucket: 'projectshowcase-b2748.firebasestorage.app',
    iosBundleId: 'com.example.projectshowcase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUduwQCS_4HXaEmn_Ilf57BxDA9DT865g',
    appId: '1:279672202046:ios:b409f9affe2a8bd4fd826f',
    messagingSenderId: '279672202046',
    projectId: 'projectshowcase-b2748',
    storageBucket: 'projectshowcase-b2748.firebasestorage.app',
    iosBundleId: 'com.example.projectshowcase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUduwQCS_4HXaEmn_Ilf57BxDA9DT865g',
    appId: '1:279672202046:web:b409f9affe2a8bd4fd826f',
    messagingSenderId: '279672202046',
    projectId: 'projectshowcase-b2748',
    authDomain: 'projectshowcase-b2748.firebaseapp.com',
    storageBucket: 'projectshowcase-b2748.firebasestorage.app',
  );
}
